name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, beta]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        apm ci
        apm install sync-settings
    - name: Run tests 👩🏾‍💻
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "test"
        atom --test spec

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: NPM install
        run: npm ci
      - name: Lint ✨
        run: npm run lint

  Release:
    needs: [Test, Lint]
    if: |
      github.ref == 'refs/heads/master' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: NPM install
        run: npm ci
      - name: Release 🎉
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATOM_ACCESS_TOKEN: ${{ secrets.ATOM_ACCESS_TOKEN }}
        run: npx semantic-release

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
